# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Automatic Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    if: contains(github.event.head_commit_message, 'build')

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install argparse httpx h2 datetime ossapi pyinstaller colorama
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build application
      run: |
        pyinstaller --onefile osufetch.py
    - name: Get version
      run : echo "::set-output name=version::$(./dist/osufetch --version)"
      id: version
    - name: Create release
      uses: actions/create-release@v1
      id: create_release
      with:
        tag_name: v${{ steps.version.outputs.version }}
        release_name: v${{ steps.version.outputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload artifact to release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/osufetch
        asset_name: osufetch
        asset_content_type: application
    - name: Upload PKGBuild to AUR
      uses: KSXGitHub/github-actions-deploy-aur@v4.1.1
      with:
        pkgname: osufetch-bin
        pkgbuild: ./PKGBUILD
        commit_username: ${{ secrets.AUR_USERNAME }}
        commit_email: ${{ secrets.AUR_EMAIL }}
        ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
        commit_message: Update AUR
        ssh_keyscan_types: rsa,ecdsa,ed25519
        updpkgsums: true



