# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python eblya

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install argparse httpx h2 datetime ossapi pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build application
      run: |
        pyinstaller --onefile osufetch.py
    - name: Upload release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag: ${{ github.ref }}
        files: |
          dist/osufetch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



